namespace Todo.Core.Services;

public class LocalizationService
{
    private readonly AppSettingsService _settings;

    public LocalizationService(AppSettingsService settings)
    {
        _settings = settings;
        _settings.OnLanguageChanged += () => OnLanguageChanged?.Invoke();
    }

    public string Lang => _settings.Language;
    public event Action? OnLanguageChanged;

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        var dict = Lang == "en" ? En : Fr;
        return dict.TryGetValue(key, out var value) ? value : key;
    }

    private static readonly Dictionary<string, string> Fr = new()
    {
        // ── Common ──
        ["Save"] = "Enregistrer",
        ["Cancel"] = "Annuler",
        ["Delete"] = "Supprimer",
        ["Confirm"] = "Confirmer",
        ["Close"] = "Fermer",
        ["Add"] = "+ Ajouter",
        ["Edit"] = "Modifier",
        ["Create"] = "Créer",
        ["Back"] = "Retour",
        ["Name"] = "Nom",
        ["Color"] = "Couleur",
        ["Order"] = "Ordre",
        ["Type"] = "Type",
        ["Saved"] = "Enregistré.",
        ["Error"] = "Erreur",

        // ── Home ──
        ["HomeTitle"] = "Todo - Projets",
        ["Projects"] = "Projets",
        ["NewProjectPlaceholder"] = "Nom du nouveau projet...",
        ["DeleteProjectConfirm"] = "Supprimer le projet",
        ["DeleteProjectWarning"] = "Tous les tickets et données associés seront définitivement supprimés.",
        ["Pause"] = "Mettre en pause",
        ["Resume"] = "Reprendre",
        ["Paused"] = "En pause",

        // ── Board ──
        ["ProjectNotFound"] = "Projet introuvable.",
        ["BackToProjects"] = "Projets",
        ["MainBoard"] = "Board principal",
        ["Filter"] = "Filtrer…",
        ["FilterSyntax"] = "Syntaxe de filtre",
        ["FilterByNumber"] = "ticket par numéro",
        ["FilterAssignedTo"] = "assigné à",
        ["FilterAfter"] = "modifié après",
        ["FilterBefore"] = "modifié avant",
        ["FilterByPriority"] = "par priorité",
        ["FilterByLabel"] = "par label",
        ["FilterCreatedBy"] = "créé par",
        ["FilterFreeText"] = "Texte libre = titre, description, commentaires",
        ["UndoNothing"] = "Rien à annuler (Ctrl+Z)",
        ["UndoPrefix"] = "Annuler",
        ["Automations"] = "Automations",
        ["ProjectSettings"] = "Paramètres",
        ["ProjectSettingsTooltip"] = "Paramètres du projet",
        ["PlaceHere"] = "Placer ici",
        ["ViewSubTickets"] = "Voir les sous-tickets",
        ["Unparent"] = "Dissocier",
        ["DeleteColumnConfirm"] = "Supprimer la colonne",
        ["MoveTicketsTo"] = "Les tickets seront déplacés vers :",
        ["DeleteTicketConfirm"] = "Supprimer le ticket",
        ["NewTicket"] = "Nouveau ticket",
        ["Title"] = "Titre",
        ["TicketTitlePlaceholder"] = "Titre du ticket...",
        ["Description"] = "Description",
        ["DescriptionMarkdown"] = "Description (Markdown)",
        ["DescriptionPlaceholder"] = "Description...",
        ["Priority"] = "Priorité",
        ["Labels"] = "Labels",
        ["AssignTo"] = "Assigner à",
        ["Unassigned"] = "— Non assigné —",
        ["CreateTicket"] = "Créer le ticket",
        ["ChangePriority"] = "Changer la priorité",
        ["EditTitle"] = "Modifier le titre",
        ["EditDescription"] = "Modifier la description",
        ["NoDescription"] = "Aucune description — cliquez sur ✎ pour en ajouter une.",
        ["Activity"] = "Activité",
        ["AddComment"] = "+ Commentaire",
        ["DeleteThisTicket"] = "Supprimer ce ticket",
        ["DeleteThisTicketConfirm"] = "Supprimer ce ticket ?",
        ["LabelManagement"] = "Gestion des labels",
        ["LabelNamePlaceholder"] = "Nom du label",
        ["NewLabelPlaceholder"] = "Nouveau label...",
        ["MemberManagement"] = "Gestion des membres",
        ["NewMemberPlaceholder"] = "Nouveau membre...",
        ["AssignedToLabel"] = "Assigné à :",
        ["AssignPlaceholder"] = "+ Assigner...",
        ["ChangePlaceholder"] = "Changer...",
        ["SubTickets"] = "Sous-tickets",
        ["ViewAll"] = "Voir tout",
        ["Parent"] = "Parent :",
        ["Comment"] = "Commentaire",
        ["ViewLastRun"] = "Voir le dernier run",
        ["FullscreenDescription"] = "Description",
        ["FullscreenComment"] = "Commentaire",

        // ── Priority labels ──
        ["PriorityIdea"] = "Idée",
        ["PriorityNiceToHave"] = "Optionnel",
        ["PriorityRequired"] = "Requis",
        ["PriorityCritical"] = "Critique",

        // ── Undo labels ──
        ["UndoDescription"] = "Description",
        ["UndoMove"] = "Déplacer",
        ["UndoUnparent"] = "Dissocier",
        ["UndoAssociate"] = "Associer",
        ["UndoLabel"] = "Label",
        ["UndoAssign"] = "Assigner",
        ["UndoUnassign"] = "Désassigner",
        ["UndoDelete"] = "Supprimer",
        ["UndoRename"] = "Renommer",
        ["UndoCreate"] = "Créer",
        ["UndoPriority"] = "Priorité",
        ["UndoColumn"] = "Colonne",
        ["UndoComment"] = "Commentaire",

        // ── ProjectSettings ──
        ["SettingsTitle"] = "Paramètres",
        ["Board"] = "Board",
        ["WorkspacePath"] = "Dossier de travail",
        ["WorkspaceHint"] = "Chemin absolu vers le repo / dossier du projet. C'est là que sera chargé le .claude/ et que sera lu .agents/automations.json.",
        ["WorkspacePlaceholder"] = @"D:\Sources\…",
        ["Browse"] = "Parcourir",
        ["Members"] = "Membres",
        ["MembersHint"] = "Les membres servent à assigner des tickets. Les automations ciblent un membre par son slug (champ assigneeSlug).",
        ["Slug"] = "Slug",
        ["NewMemberSettingsPlaceholder"] = "Nouveau membre…",
        ["Columns"] = "Colonnes",
        ["ColumnsHint"] = "Colonnes du kanban. L'ordre est appliqué via la flèche haut/bas.",
        ["NewColumnPlaceholder"] = "Nouvelle colonne…",
        ["LabelsSection"] = "Labels",
        ["LabelsHint"] = "Tags réutilisables pour catégoriser les tickets.",
        ["NewLabelSettingsPlaceholder"] = "Nouveau label…",
        ["OpenAutomationsEditor"] = "Ouvrir l'éditeur d'automations →",

        // ── Automations ──
        ["ReloadFromDisk"] = "Relire automations.json depuis le disque",
        ["Reload"] = "Recharger",
        ["NewAutomation"] = "+ Automation",
        ["NoAutomations"] = "Aucune automation. Clique sur \"+ Automation\" pour commencer.",
        ["Unnamed"] = "(sans nom)",
        ["Run"] = "Exécuter",
        ["RunNow"] = "Exécuter maintenant",
        ["EditNode"] = "Éditer le nœud",
        ["AutomationNamePlaceholder"] = "Nom de l'automation",
        ["Enabled"] = "Activé",
        ["RunLaunched"] = "Exécution de '{0}' lancée.",
        ["NewAutomationName"] = "Nouvelle automation",
        ["DragToMove"] = "Glisser pour déplacer",

        // ── Trigger descriptions ──
        ["TrigCron"] = "cron {0}",
        ["TrigInterval"] = "toutes les {0}s",
        ["TrigTicketInColumn"] = "ticket dans [{0}]",
        ["TrigTicketAssigned"] = "assigné={0}",
        ["TrigGitCommit"] = "après commit git ({0}s)",
        ["TrigStatusChange"] = "statut {0} → {1}",
        ["TrigSubTickets"] = "sous-tickets changés ({0})",
        ["TrigBoardIdle"] = "board idle",
        ["TrigAgentInactivity"] = "inactivité {0}min",

        // ── Condition descriptions ──
        ["CondInColumn"] = "dans [{0}]",
        ["CondNoPending"] = "aucun ticket en cours ({0})",
        ["CondNoPendingAll"] = "tous",
        ["CondMinDesc"] = "desc ≥ {0} car.",
        ["CondFieldLength"] = "{0} {1} {2} car.",
        ["CondPriority"] = "priorité ∈ [{0}]",
        ["CondLabels"] = "labels ∈ [{0}]",
        ["CondAssignedTo"] = "assigné à [{0}]",
        ["CondNotAssignedTo"] = "non assigné à [{0}]",
        ["CondTicketAge"] = "{0} {1} {2}h",
        ["CondHasParentTrue"] = "sous-ticket",
        ["CondHasParentFalse"] = "racine",

        // ── Action descriptions ──
        ["ActionMoveTo"] = "→ {0}",
        ["ActionSetLabelsDesc"] = "+[{0}] −[{1}]",

        // ── ActionEditor ──
        ["ActionType"] = "Type",
        ["ActionRunSkill"] = "Exécuter un skill Claude",
        ["ActionMoveTicket"] = "Déplacer le ticket",
        ["ActionSetLabels"] = "Modifier les labels",
        ["ActionAssignTicket"] = "Réassigner le ticket",
        ["ActionAddComment"] = "Poster un commentaire",
        ["CommentContent"] = "Contenu du commentaire",
        ["CommentContentPlaceholder"] = "Ticket #{ticketId} reçu par {assignee}…",
        ["CommentAuthor"] = "Auteur",
        ["AssignTo"] = "Assigner à",
        ["Nobody"] = "personne",
        ["LabelsToAdd"] = "Labels à ajouter (noms, séparés par virgule)",
        ["LabelsToRemove"] = "Labels à retirer (noms, séparés par virgule)",
        ["LabelsCsvPlaceholder"] = "agent-done, reviewed…",
        ["SkillFile"] = "Fichier skill (relatif à .agents/)",
        ["AgentName"] = "Nom d'agent (par défaut = nom du fichier)",
        ["AgentNamePlaceholder"] = "(auto)",
        ["MaxTurns"] = "Max turns",
        ["ConcurrencyGroup"] = "Groupe de concurrence (exclusif)",
        ["ConcurrencyPlaceholder"] = "code, producer, ceo…",
        ["MutuallyExclusive"] = "Exclusif avec (groupes, séparés par virgules)",
        ["ClaudeModel"] = "Modèle Claude (optionnel)",
        ["ModelDefault"] = "(défaut)",
        ["ModelCustom"] = "(custom)",
        ["NewColumn"] = "Nouvelle colonne",
        ["DeleteAction"] = "Supprimer l'action",

        // ── ConditionEditor ──
        ["CondTypeTicketInColumn"] = "Ticket dans colonne",
        ["CondTypeNoPending"] = "Aucun ticket en cours",
        ["CondTypeFieldLength"] = "Longueur de champ",
        ["CondTypePriority"] = "Priorité",
        ["CondTypeLabels"] = "Labels",
        ["CondTypeAssignedTo"] = "Assigné à",
        ["CondTypeTicketAge"] = "Âge du ticket",
        ["CondTypeHasParent"] = "Hiérarchie (racine/sous-ticket)",
        ["HasParentLabel"] = "Est un sous-ticket",
        ["Negate"] = "Inverser (NOT)",
        ["ColumnsOneOrMore"] = "Colonnes (une ou plusieurs)",
        ["AssigneeOptional"] = "Assigné (slug, optionnel)",
        ["AnyMember"] = "— n'importe qui —",
        ["AssigneeAll"] = "Assigné (slug, laisser vide = tous)",
        ["All"] = "— tous —",
        ["MinLength"] = "Longueur min.",
        ["Field"] = "Champ",
        ["Mode"] = "Mode",
        ["CharCount"] = "Nb caractères",
        ["FieldDescription"] = "Description",
        ["FieldTitle"] = "Titre",
        ["ModeMin"] = "Minimum",
        ["ModeMax"] = "Maximum",
        ["ModeOlderThan"] = "Plus ancien que",
        ["ModeNewerThan"] = "Plus récent que",
        ["FieldCreatedAt"] = "Date de création",
        ["FieldUpdatedAt"] = "Date de mise à jour",
        ["Hours"] = "Heures",
        ["PrioritiesOneOrMore"] = "Priorités (une ou plusieurs)",
        ["LabelsCsv"] = "Labels (séparés par virgule)",
        ["AssignedToOneOrMore"] = "Assigné à (un ou plusieurs)",
        ["DeleteCondition"] = "Supprimer la condition",

        // ── TriggerEditor ──
        ["TrigTypeInterval"] = "Intervalle / cron",
        ["TrigTypeTicketInColumn"] = "Ticket dans colonne",
        ["TrigTypeGitCommit"] = "Après commit git",
        ["TrigTypeStatusChange"] = "Changement de statut",
        ["TrigTypeSubTickets"] = "Sous-tickets changés",
        ["TrigTypeBoardIdle"] = "Board idle",
        ["TrigTypeAgentInactivity"] = "Inactivité agents",
        ["TrigTypeCommentAdded"] = "Commentaire ajouté",
        ["AuthorsFilterHint"] = "Auteurs (virgules, vide = tous)",
        ["IgnoreAuthorsHint"] = "Ignorer auteurs (emails séparés par virgules)",
        ["IntervalSeconds"] = "Intervalle (secondes)",
        ["CronLabel"] = "Cron (prioritaire si défini)",
        ["CronPlaceholder"] = "0 2 * * *",
        ["PollSeconds"] = "Poll (secondes)",
        ["AssigneeMemberOptional"] = "Assigné (optionnel — slug du membre)",
        ["AnyMemberOption"] = "— n'importe quel membre —",
        ["FromOptional"] = "Depuis (optionnel)",
        ["ToOptional"] = "Vers (optionnel)",
        ["AnyOption"] = "— n'importe —",
        ["DebounceSeconds"] = "Debounce (secondes, optionnel)",
        ["ParentColumnOptional"] = "Colonne des tickets parents (optionnel)",
        ["AllColumns"] = "— toutes —",
        ["IdleColumnsHint"] = "Colonnes considérées comme \"idle\" (le board est idle quand tous les tickets y sont)",
        ["InactivityMinutes"] = "Minutes d'inactivité avant déclenchement",

        // ── NodePalette ──
        ["PaletteTriggers"] = "Triggers",
        ["PaletteConditions"] = "Conditions",
        ["PaletteActions"] = "Actions",
        ["PaletteDragHint"] = "Glisse un nœud vers le flow →",
        ["PalTrigInterval"] = "Intervalle / cron",
        ["PalTrigIntervalHint"] = "Déclenche à intervalle régulier ou selon un cron",
        ["PalTrigTicketInColumn"] = "Ticket dans colonne",
        ["PalTrigTicketInColumnHint"] = "Déclenche quand un ticket est dans une colonne donnée",
        ["PalTrigGitCommit"] = "Après commit git",
        ["PalTrigGitCommitHint"] = "Déclenche quand un nouveau commit est détecté",
        ["PalTrigStatusChange"] = "Changement de statut",
        ["PalTrigStatusChangeHint"] = "Déclenche quand un ticket change de colonne",
        ["PalTrigSubTickets"] = "Sous-tickets changés",
        ["PalTrigSubTicketsHint"] = "Déclenche quand le CSV des statuts de sous-tickets change",
        ["PalTrigBoardIdle"] = "Board idle",
        ["PalTrigBoardIdleHint"] = "Déclenche quand tous les tickets sont dans les colonnes 'idle'",
        ["PalTrigAgentInactivity"] = "Inactivité agents",
        ["PalTrigAgentInactivityHint"] = "Déclenche après N minutes sans dispatch",
        ["PalCondTicketInColumn"] = "Ticket dans colonne",
        ["PalCondTicketInColumnHint"] = "N'exécute que si le ticket est dans une colonne",
        ["PalCondNoPending"] = "Aucun ticket en cours",
        ["PalCondNoPendingHint"] = "N'exécute que si aucun ticket n'est en cours",
        ["PalCondFieldLength"] = "Longueur de champ",
        ["PalCondFieldLengthHint"] = "Vérifie la longueur du titre ou de la description (min/max)",
        ["PalCondPriority"] = "Priorité",
        ["PalCondPriorityHint"] = "Filtre sur la priorité du ticket",
        ["PalCondLabels"] = "Labels",
        ["PalCondLabelsHint"] = "Filtre sur les labels du ticket",
        ["PalCondAssignedTo"] = "Assigné à",
        ["PalCondAssignedToHint"] = "Filtre sur l'assignation du ticket",
        ["PalCondTicketAge"] = "Âge du ticket",
        ["PalCondTicketAgeHint"] = "Filtre par ancienneté de création ou mise à jour",
        ["PalActRunSkill"] = "Exécuter un skill",
        ["PalActRunSkillHint"] = "Lance claude avec un fichier skill",
        ["PalActMoveTicket"] = "Déplacer le ticket",
        ["PalActMoveTicketHint"] = "Change le statut du ticket",
        ["PalActSetLabels"] = "Modifier les labels",
        ["PalActSetLabelsHint"] = "Ajoute ou retire des labels du ticket",
        ["PalActAssignTicket"] = "Réassigner le ticket",
        ["PalActAssignTicketHint"] = "Change l'assigné du ticket",
        ["PalActAddComment"] = "Poster un commentaire",
        ["PalActAddCommentHint"] = "Ajoute un commentaire au ticket sans invoquer Claude",

        // ── AgentRunDrawer ──
        ["StopAgent"] = "Arrêter l'agent",
        ["Stop"] = "Stop",
        ["WaitingForOutput"] = "En attente de la sortie…",
        ["SteerPlaceholder"] = "Envoyer une instruction à l'agent…",
        ["Send"] = "Envoyer",

        // ── DropSlot ──
        ["DropHere"] = "Déposer ici",

        // ── Language switcher ──
        ["Language"] = "Langue",
        ["LangFr"] = "Français",
        ["LangEn"] = "English",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        // ── Common ──
        ["Save"] = "Save",
        ["Cancel"] = "Cancel",
        ["Delete"] = "Delete",
        ["Confirm"] = "Confirm",
        ["Close"] = "Close",
        ["Add"] = "+ Add",
        ["Edit"] = "Edit",
        ["Create"] = "Create",
        ["Back"] = "Back",
        ["Name"] = "Name",
        ["Color"] = "Color",
        ["Order"] = "Order",
        ["Type"] = "Type",
        ["Saved"] = "Saved.",
        ["Error"] = "Error",

        // ── Home ──
        ["HomeTitle"] = "Todo - Projects",
        ["Projects"] = "Projects",
        ["NewProjectPlaceholder"] = "New project name...",
        ["DeleteProjectConfirm"] = "Delete project",
        ["DeleteProjectWarning"] = "All tickets and associated data will be permanently deleted.",
        ["Pause"] = "Pause",
        ["Resume"] = "Resume",
        ["Paused"] = "Paused",

        // ── Board ──
        ["ProjectNotFound"] = "Project not found.",
        ["BackToProjects"] = "Projects",
        ["MainBoard"] = "Main board",
        ["Filter"] = "Filter…",
        ["FilterSyntax"] = "Filter syntax",
        ["FilterByNumber"] = "ticket by number",
        ["FilterAssignedTo"] = "assigned to",
        ["FilterAfter"] = "modified after",
        ["FilterBefore"] = "modified before",
        ["FilterByPriority"] = "by priority",
        ["FilterByLabel"] = "by label",
        ["FilterCreatedBy"] = "created by",
        ["FilterFreeText"] = "Free text = title, description, comments",
        ["UndoNothing"] = "Nothing to undo (Ctrl+Z)",
        ["UndoPrefix"] = "Undo",
        ["Automations"] = "Automations",
        ["ProjectSettings"] = "Settings",
        ["ProjectSettingsTooltip"] = "Project settings",
        ["PlaceHere"] = "Place here",
        ["ViewSubTickets"] = "View sub-tickets",
        ["Unparent"] = "Unlink",
        ["DeleteColumnConfirm"] = "Delete column",
        ["MoveTicketsTo"] = "Tickets will be moved to:",
        ["DeleteTicketConfirm"] = "Delete ticket",
        ["NewTicket"] = "New ticket",
        ["Title"] = "Title",
        ["TicketTitlePlaceholder"] = "Ticket title...",
        ["Description"] = "Description",
        ["DescriptionMarkdown"] = "Description (Markdown)",
        ["DescriptionPlaceholder"] = "Description...",
        ["Priority"] = "Priority",
        ["Labels"] = "Labels",
        ["AssignTo"] = "Assign to",
        ["Unassigned"] = "— Unassigned —",
        ["CreateTicket"] = "Create ticket",
        ["ChangePriority"] = "Change priority",
        ["EditTitle"] = "Edit title",
        ["EditDescription"] = "Edit description",
        ["NoDescription"] = "No description — click ✎ to add one.",
        ["Activity"] = "Activity",
        ["AddComment"] = "+ Comment",
        ["DeleteThisTicket"] = "Delete this ticket",
        ["DeleteThisTicketConfirm"] = "Delete this ticket?",
        ["LabelManagement"] = "Label management",
        ["LabelNamePlaceholder"] = "Label name",
        ["NewLabelPlaceholder"] = "New label...",
        ["MemberManagement"] = "Member management",
        ["NewMemberPlaceholder"] = "New member...",
        ["AssignedToLabel"] = "Assigned to:",
        ["AssignPlaceholder"] = "+ Assign...",
        ["ChangePlaceholder"] = "Change...",
        ["SubTickets"] = "Sub-tickets",
        ["ViewAll"] = "View all",
        ["Parent"] = "Parent:",
        ["Comment"] = "Comment",
        ["ViewLastRun"] = "View last run",
        ["FullscreenDescription"] = "Description",
        ["FullscreenComment"] = "Comment",

        // ── Priority labels ──
        ["PriorityIdea"] = "Idea",
        ["PriorityNiceToHave"] = "Nice to have",
        ["PriorityRequired"] = "Required",
        ["PriorityCritical"] = "Critical",

        // ── Undo labels ──
        ["UndoDescription"] = "Description",
        ["UndoMove"] = "Move",
        ["UndoUnparent"] = "Unlink",
        ["UndoAssociate"] = "Associate",
        ["UndoLabel"] = "Label",
        ["UndoAssign"] = "Assign",
        ["UndoUnassign"] = "Unassign",
        ["UndoDelete"] = "Delete",
        ["UndoRename"] = "Rename",
        ["UndoCreate"] = "Create",
        ["UndoPriority"] = "Priority",
        ["UndoColumn"] = "Column",
        ["UndoComment"] = "Comment",

        // ── ProjectSettings ──
        ["SettingsTitle"] = "Settings",
        ["Board"] = "Board",
        ["WorkspacePath"] = "Workspace path",
        ["WorkspaceHint"] = "Absolute path to the project repo/folder. This is where .claude/ is loaded and .agents/automations.json is read.",
        ["WorkspacePlaceholder"] = @"D:\Sources\…",
        ["Browse"] = "Browse",
        ["Members"] = "Members",
        ["MembersHint"] = "Members are used to assign tickets. Automations target a member by slug (assigneeSlug field).",
        ["Slug"] = "Slug",
        ["NewMemberSettingsPlaceholder"] = "New member…",
        ["Columns"] = "Columns",
        ["ColumnsHint"] = "Kanban columns. Order is set via up/down arrows.",
        ["NewColumnPlaceholder"] = "New column…",
        ["LabelsSection"] = "Labels",
        ["LabelsHint"] = "Reusable tags to categorize tickets.",
        ["NewLabelSettingsPlaceholder"] = "New label…",
        ["OpenAutomationsEditor"] = "Open automations editor →",

        // ── Automations ──
        ["ReloadFromDisk"] = "Reload automations.json from disk",
        ["Reload"] = "Reload",
        ["NewAutomation"] = "+ Automation",
        ["NoAutomations"] = "No automations. Click \"+ Automation\" to get started.",
        ["Unnamed"] = "(unnamed)",
        ["Run"] = "Run",
        ["RunNow"] = "Run now",
        ["EditNode"] = "Edit node",
        ["AutomationNamePlaceholder"] = "Automation name",
        ["Enabled"] = "Enabled",
        ["RunLaunched"] = "Run '{0}' launched.",
        ["NewAutomationName"] = "New automation",
        ["DragToMove"] = "Drag to move",

        // ── Trigger descriptions ──
        ["TrigCron"] = "cron {0}",
        ["TrigInterval"] = "every {0}s",
        ["TrigTicketInColumn"] = "ticket in [{0}]",
        ["TrigTicketAssigned"] = "assigned={0}",
        ["TrigGitCommit"] = "after git commit ({0}s)",
        ["TrigStatusChange"] = "status {0} → {1}",
        ["TrigSubTickets"] = "sub-tickets changed ({0})",
        ["TrigBoardIdle"] = "board idle",
        ["TrigAgentInactivity"] = "inactivity {0}min",

        // ── Condition descriptions ──
        ["CondInColumn"] = "in [{0}]",
        ["CondNoPending"] = "no pending tickets ({0})",
        ["CondNoPendingAll"] = "all",
        ["CondMinDesc"] = "desc ≥ {0} chars",
        ["CondFieldLength"] = "{0} {1} {2} chars",
        ["CondPriority"] = "priority ∈ [{0}]",
        ["CondLabels"] = "labels ∈ [{0}]",
        ["CondAssignedTo"] = "assigned to [{0}]",
        ["CondNotAssignedTo"] = "not assigned to [{0}]",
        ["CondTicketAge"] = "{0} {1} {2}h",
        ["CondHasParentTrue"] = "sub-ticket",
        ["CondHasParentFalse"] = "root ticket",

        // ── Action descriptions ──
        ["ActionMoveTo"] = "→ {0}",
        ["ActionSetLabelsDesc"] = "+[{0}] −[{1}]",

        // ── ActionEditor ──
        ["ActionType"] = "Type",
        ["ActionRunSkill"] = "Run Claude skill",
        ["ActionMoveTicket"] = "Move ticket",
        ["ActionSetLabels"] = "Set labels",
        ["ActionAssignTicket"] = "Assign ticket",
        ["ActionAddComment"] = "Post a comment",
        ["CommentContent"] = "Comment content",
        ["CommentContentPlaceholder"] = "Ticket #{ticketId} received by {assignee}…",
        ["CommentAuthor"] = "Author",
        ["AssignTo"] = "Assign to",
        ["Nobody"] = "nobody",
        ["LabelsToAdd"] = "Labels to add (names, comma-separated)",
        ["LabelsToRemove"] = "Labels to remove (names, comma-separated)",
        ["LabelsCsvPlaceholder"] = "agent-done, reviewed…",
        ["SkillFile"] = "Skill file (relative to .agents/)",
        ["AgentName"] = "Agent name (default = file name)",
        ["AgentNamePlaceholder"] = "(auto)",
        ["MaxTurns"] = "Max turns",
        ["ConcurrencyGroup"] = "Concurrency group (exclusive)",
        ["ConcurrencyPlaceholder"] = "code, producer, ceo…",
        ["MutuallyExclusive"] = "Mutually exclusive with (groups, comma-separated)",
        ["ClaudeModel"] = "Claude model (optional)",
        ["ModelDefault"] = "(default)",
        ["ModelCustom"] = "(custom)",
        ["NewColumn"] = "New column",
        ["DeleteAction"] = "Delete action",

        // ── ConditionEditor ──
        ["CondTypeTicketInColumn"] = "Ticket in column",
        ["CondTypeNoPending"] = "No pending tickets",
        ["CondTypeFieldLength"] = "Field length",
        ["CondTypePriority"] = "Priority",
        ["CondTypeLabels"] = "Labels",
        ["CondTypeAssignedTo"] = "Assigned to",
        ["CondTypeTicketAge"] = "Ticket age",
        ["CondTypeHasParent"] = "Hierarchy (root/sub-ticket)",
        ["HasParentLabel"] = "Is a sub-ticket",
        ["Negate"] = "Negate (NOT)",
        ["ColumnsOneOrMore"] = "Columns (one or more)",
        ["AssigneeOptional"] = "Assignee (slug, optional)",
        ["AnyMember"] = "— anyone —",
        ["AssigneeAll"] = "Assignee (slug, leave empty = all)",
        ["All"] = "— all —",
        ["MinLength"] = "Min length",
        ["Field"] = "Field",
        ["Mode"] = "Mode",
        ["CharCount"] = "Character count",
        ["FieldDescription"] = "Description",
        ["FieldTitle"] = "Title",
        ["ModeMin"] = "Minimum",
        ["ModeMax"] = "Maximum",
        ["ModeOlderThan"] = "Older than",
        ["ModeNewerThan"] = "Newer than",
        ["FieldCreatedAt"] = "Created at",
        ["FieldUpdatedAt"] = "Updated at",
        ["Hours"] = "Hours",
        ["PrioritiesOneOrMore"] = "Priorities (one or more)",
        ["LabelsCsv"] = "Labels (comma-separated)",
        ["AssignedToOneOrMore"] = "Assigned to (one or more)",
        ["DeleteCondition"] = "Delete condition",

        // ── TriggerEditor ──
        ["TrigTypeInterval"] = "Interval / cron",
        ["TrigTypeTicketInColumn"] = "Ticket in column",
        ["TrigTypeGitCommit"] = "After git commit",
        ["TrigTypeStatusChange"] = "Status change",
        ["TrigTypeSubTickets"] = "Sub-tickets changed",
        ["TrigTypeBoardIdle"] = "Board idle",
        ["TrigTypeAgentInactivity"] = "Agent inactivity",
        ["TrigTypeCommentAdded"] = "Comment added",
        ["AuthorsFilterHint"] = "Authors (comma-separated, empty = all)",
        ["IgnoreAuthorsHint"] = "Ignore authors (comma-separated emails)",
        ["IntervalSeconds"] = "Interval (seconds)",
        ["CronLabel"] = "Cron (takes priority if set)",
        ["CronPlaceholder"] = "0 2 * * *",
        ["PollSeconds"] = "Poll (seconds)",
        ["AssigneeMemberOptional"] = "Assignee (optional — member slug)",
        ["AnyMemberOption"] = "— any member —",
        ["FromOptional"] = "From (optional)",
        ["ToOptional"] = "To (optional)",
        ["AnyOption"] = "— any —",
        ["DebounceSeconds"] = "Debounce (seconds, optional)",
        ["ParentColumnOptional"] = "Parent tickets column (optional)",
        ["AllColumns"] = "— all —",
        ["IdleColumnsHint"] = "Columns considered \"idle\" (the board is idle when all tickets are in these)",
        ["InactivityMinutes"] = "Minutes of inactivity before triggering",

        // ── NodePalette ──
        ["PaletteTriggers"] = "Triggers",
        ["PaletteConditions"] = "Conditions",
        ["PaletteActions"] = "Actions",
        ["PaletteDragHint"] = "Drag a node to the flow →",
        ["PalTrigInterval"] = "Interval / cron",
        ["PalTrigIntervalHint"] = "Triggers at regular intervals or via cron",
        ["PalTrigTicketInColumn"] = "Ticket in column",
        ["PalTrigTicketInColumnHint"] = "Triggers when a ticket is in a given column",
        ["PalTrigGitCommit"] = "After git commit",
        ["PalTrigGitCommitHint"] = "Triggers when a new commit is detected",
        ["PalTrigStatusChange"] = "Status change",
        ["PalTrigStatusChangeHint"] = "Triggers when a ticket changes column",
        ["PalTrigSubTickets"] = "Sub-tickets changed",
        ["PalTrigSubTicketsHint"] = "Triggers when sub-ticket statuses CSV changes",
        ["PalTrigBoardIdle"] = "Board idle",
        ["PalTrigBoardIdleHint"] = "Triggers when all tickets are in 'idle' columns",
        ["PalTrigAgentInactivity"] = "Agent inactivity",
        ["PalTrigAgentInactivityHint"] = "Triggers after N minutes without dispatch",
        ["PalCondTicketInColumn"] = "Ticket in column",
        ["PalCondTicketInColumnHint"] = "Only runs if the ticket is in a column",
        ["PalCondNoPending"] = "No pending tickets",
        ["PalCondNoPendingHint"] = "Only runs if no tickets are in progress",
        ["PalCondFieldLength"] = "Field length",
        ["PalCondFieldLengthHint"] = "Checks title or description length (min/max)",
        ["PalCondPriority"] = "Priority",
        ["PalCondPriorityHint"] = "Filters on ticket priority",
        ["PalCondLabels"] = "Labels",
        ["PalCondLabelsHint"] = "Filters on ticket labels",
        ["PalCondAssignedTo"] = "Assigned to",
        ["PalCondAssignedToHint"] = "Filters on ticket assignment",
        ["PalCondTicketAge"] = "Ticket age",
        ["PalCondTicketAgeHint"] = "Filters by ticket creation or update age",
        ["PalActRunSkill"] = "Run a skill",
        ["PalActRunSkillHint"] = "Runs claude with a skill file",
        ["PalActMoveTicket"] = "Move ticket",
        ["PalActMoveTicketHint"] = "Changes the ticket status",
        ["PalActSetLabels"] = "Set labels",
        ["PalActSetLabelsHint"] = "Adds or removes labels from the ticket",
        ["PalActAssignTicket"] = "Assign ticket",
        ["PalActAssignTicketHint"] = "Changes the ticket assignee",
        ["PalActAddComment"] = "Post a comment",
        ["PalActAddCommentHint"] = "Adds a comment to the ticket without invoking Claude",

        // ── AgentRunDrawer ──
        ["StopAgent"] = "Stop agent",
        ["Stop"] = "Stop",
        ["WaitingForOutput"] = "Waiting for output…",
        ["SteerPlaceholder"] = "Send an instruction to the agent…",
        ["Send"] = "Send",

        // ── DropSlot ──
        ["DropHere"] = "Drop here",

        // ── Language switcher ──
        ["Language"] = "Language",
        ["LangFr"] = "Français",
        ["LangEn"] = "English",
    };
}
